# Generated by Django 2.2.5 on 2019-10-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloWorldApp', '0003_remove_suggestion_suggestion2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anImage_name', models.CharField(max_length=30)),
                ('anImage', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
