# Generated by Django 2.2.5 on 2019-10-07 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloWorldApp', '0004_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='anImage',
            new_name='an_Image',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='anImage_name',
            new_name='an_Image_name',
        ),
    ]
