# Generated by Django 2.2.5 on 2019-10-09 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloWorldApp', '0005_auto_20191007_0224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
