# Generated by Django 2.2.5 on 2019-10-27 02:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helloWorldApp', '0010_auto_20191025_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='sugg_upvote', to=settings.AUTH_USER_MODEL),
        ),
    ]
