# Generated by Django 2.2.5 on 2019-10-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloWorldApp', '0011_suggestion_upvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='image',
            field=models.ImageField(default='None', max_length=144, upload_to='uploads/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestion',
            name='image_description',
            field=models.CharField(default='', max_length=240),
            preserve_default=False,
        ),
    ]
