# Generated by Django 2.2.5 on 2019-11-12 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helloWorldApp', '0012_auto_20191027_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='upvote',
        ),
        migrations.CreateModel(
            name='Subreddit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('topics', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('members', models.IntegerField()),
                ('birthday', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(max_length=144, upload_to='subreddit/pic')),
                ('image_description', models.CharField(max_length=240)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
