# Generated by Django 2.2.5 on 2019-11-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloWorldApp', '0012_auto_20191027_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='upvote',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='header',
            field=models.CharField(default='', max_length=240),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion',
            field=models.CharField(max_length=10000),
        ),
    ]
