# Generated by Django 2.2.5 on 2019-11-13 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helloWorldApp', '0013_auto_20191112_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit',
            name='birthday',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='subreddit',
            name='image',
            field=models.ImageField(max_length=144, null=True, upload_to='subreddit/pic'),
        ),
        migrations.AlterField(
            model_name='subreddit',
            name='image_description',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='subreddit',
            name='members',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subreddit',
            name='moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
