# Generated by Django 2.2.5 on 2019-11-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloWorldApp', '0014_auto_20191112_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='video_description',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
