# Generated by Django 2.2.5 on 2019-12-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloWorldApp', '0016_auto_20191126_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='title',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
