# Generated by Django 2.2.5 on 2019-12-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloWorldApp', '0018_chatroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
