# Generated by Django 2.2.5 on 2019-12-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloWorldApp', '0022_auto_20191216_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='static/images/default.png', max_length=144, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
