# Generated by Django 2.2.5 on 2019-12-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloWorldApp', '0023_auto_20191219_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, max_length=144, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
