# Generated by Django 2.2.5 on 2019-12-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloWorldApp', '0024_auto_20191219_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='karma',
            field=models.IntegerField(default=1000),
        ),
    ]
